import "cypress-interceptor-share/e2e/beforeEach.cy";
import "cypress-interceptor-share/e2e/bigData.cy";
import "cypress-interceptor-share/e2e/custom.cy";
import "cypress-interceptor-share/e2e/mock.cy";
import "cypress-interceptor-share/e2e/serverFunctionality.cy";
import "cypress-interceptor-share/e2e/stats.cy";
import "cypress-interceptor-share/e2e/throttle.cy";
import "cypress-interceptor-share/e2e/wait.cy";
import "cypress-interceptor-share/e2e/websocket.cy";
