name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/package.json'
      - '**/package-lock.json'
      - README.md
    tags-ignore:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cache/Cypress
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: TypeScript check
        run: npm run tsc

      - name: Test
        run: npm run server & npm run test

  bump-version:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cache/Cypress
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Set creator
        run: |
          git config user.email "automated-version@users.noreply.github.com"
          git config user.name "Automated Version"

      - name: Increment version
        env:
          VERSION_TYPE: ${{ (startsWith(github.event.head_commit.message, 'BREAKING CHANGE:') || contains(toJSON(github.event.head_commit.message), '\n\nBREAKING CHANGE:')) && 'major' || (startsWith(github.event.head_commit.message, 'fix:') || contains(toJSON(github.event.head_commit.message), '\n\nfix:')) && 'patch' || 'minor' }}
        run: npm version $VERSION_TYPE -w cypress-interceptor

      - name: Push changes
        run: |
          VERSION=$(node -p "require('./packages/interceptor/package.json').version")
          git commit -am "v${VERSION}"
          git tag v${VERSION}
          git push --tags
          git push

      - name: Copy README
        run: cp README.md packages/interceptor

      - name: Publish package
        run: |
          npm config set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" 
          npm publish -w cypress-interceptor
